use std::collections::BTreeSet;
use super::*;
use rand::random;

pub struct Database {
    pub systems:      Vec<System>,
    pub blades:       Vec<Blade>,
    pub motherboards: Vec<Motherboard>,
    pub memory:       Vec<Memory>,
    pub processors:   Vec<Processor>,
}

impl Database {
    /// Create a new database
    pub fn new() -> Self {
        let systems = [
            // A non-blade server system. This is just a dummy "free" system
            // that will contain a full server as the "blade" it holds
            System {
                manufacturer: "<none>",
                name:         "<none>",
                price:        0.00,
                blade_type:   BladeType::None,
                num_blades:   1,
                blades:       Vec::new(),
            },

            System {
                manufacturer: "Supermicro",
                name:         "SBE-614E-422",
                price:        3668.00 + 407.50 + 1886.00,
                blade_type:   BladeType::SBE614E,
                num_blades:   14,
                blades:       Vec::new(),
            },
            
            System {
                manufacturer: "Supermicro",
                name:         "SBE-610J-422",
                price:        4086.00 + 407.50 + 1886.00,
                blade_type:   BladeType::SBE610J,
                num_blades:   10,
                blades:       Vec::new(),
            },
        ];

        let blades = [
            Blade {
                manufacturer:   "Supermicro",
                name:           "SuperServer 7089P-TR4iT",
                price:          16433.00,
                blade_type:     BladeType::None,
                mb_form_factor: BTreeSet::new(),
                motherboard:    Some(Motherboard {
                    manufacturer:      "Supermicro",
                    name:              "Super X11OPi-CPU",
                    price:             0.00, // Included in blade
                    form_factor:       MotherboardFormFactor::X11OPi,
                    proc_support:      ProcessorType::XeonScalableV2_FCLGA3647,
                    scalability:       8,
                    memory_sockets:    96,
                    dimms_per_channel: 2,
                    processors:        Vec::new(),
                    memory:            Vec::new(),
                }),
            },
            Blade {
                manufacturer:   "Supermicro",
                name:           "SuperServer 2049U-TR4",
                price:          3024.00,
                blade_type:     BladeType::None,
                mb_form_factor: BTreeSet::new(),
                motherboard:    Some(Motherboard {
                    manufacturer:      "Supermicro",
                    name:              "Super X11QPH+",
                    price:             0.00, // Included in blade
                    form_factor:       MotherboardFormFactor::X11QPHp,
                    proc_support:      ProcessorType::XeonScalableV2_FCLGA3647,
                    scalability:       4,
                    memory_sockets:    48,
                    dimms_per_channel: 2,
                    processors:        Vec::new(),
                    memory:            Vec::new(),
                }),
            },
            Blade {
                manufacturer:   "Supermicro",
                name:           "SBI-6119R-T3N",
                price:          637.00,
                blade_type:     BladeType::SBE610J,
                mb_form_factor: BTreeSet::new(),
                motherboard:    Some(Motherboard {
                    manufacturer:      "Supermicro",
                    name:              "Super B11SRE-CPU-TF",
                    price:             0.00, // Included in blade
                    form_factor:       MotherboardFormFactor::B11SRE,
                    proc_support:      ProcessorType::XeonW_FCLGA2066,
                    scalability:       1,
                    memory_sockets:    8,
                    dimms_per_channel: 2,
                    processors:        Vec::new(),
                    memory:            Vec::new(),
                }),
            },
            Blade {
                manufacturer:   "Supermicro",
                name:           "SBI-6119P-C3N",
                price:          761.00,
                blade_type:     BladeType::SBE610J,
                mb_form_factor: BTreeSet::new(),
                motherboard:    Some(Motherboard {
                    manufacturer:      "Supermicro",
                    name:              "Super B11SPE-CPU-TF",
                    price:             0.00, // Included in blade
                    form_factor:       MotherboardFormFactor::B11SPE,
                    proc_support:      ProcessorType::XeonScalableV2_FCLGA3647,
                    scalability:       1,
                    memory_sockets:    12,
                    dimms_per_channel: 2,
                    processors:        Vec::new(),
                    memory:            Vec::new(),
                }),
            },
            Blade {
                manufacturer:   "Supermicro",
                name:           "SBI-6129P-T3N",
                price:          785.50,
                blade_type:     BladeType::SBE610J,
                mb_form_factor: BTreeSet::new(),
                motherboard:    Some(Motherboard {
                    manufacturer:      "Supermicro",
                    name:              "Super B11DPE",
                    price:             0.00, // Included in blade
                    form_factor:       MotherboardFormFactor::B11DPE,
                    proc_support:      ProcessorType::XeonScalableV2_FCLGA3647,
                    scalability:       2,
                    memory_sockets:    24,
                    dimms_per_channel: 2,
                    processors:        Vec::new(),
                    memory:            Vec::new(),
                }),
            },
            Blade {
                manufacturer:   "Supermicro",
                name:           "SBI-6419P-C3N",
                price:          752.00,
                blade_type:     BladeType::SBE614E,
                mb_form_factor: BTreeSet::new(),
                motherboard:    Some(Motherboard {
                    manufacturer:      "Supermicro",
                    name:              "Super B11SPE-CPU-TF",
                    price:             0.00, // Included in blade
                    form_factor:       MotherboardFormFactor::B11SPE,
                    proc_support:      ProcessorType::XeonScalableV2_FCLGA3647,
                    scalability:       1,
                    memory_sockets:    12,
                    dimms_per_channel: 2,
                    processors:        Vec::new(),
                    memory:            Vec::new(),
                }),
            },
            Blade {
                manufacturer:   "Supermicro",
                name:           "SBI-6429P-T3N",
                price:          766.50,
                blade_type:     BladeType::SBE614E,
                mb_form_factor: BTreeSet::new(),
                motherboard:    Some(Motherboard {
                    manufacturer:      "Supermicro",
                    name:              "Super B11DPE",
                    price:             0.00, // Included in blade
                    form_factor:       MotherboardFormFactor::B11DPE,
                    proc_support:      ProcessorType::XeonScalableV2_FCLGA3647,
                    scalability:       2,
                    memory_sockets:    24,
                    dimms_per_channel: 2,
                    processors:        Vec::new(),
                    memory:            Vec::new(),
                }),
            },
        ];

        let motherboards = [];

        let memory = [
            Memory {
                manufacturer: "Kingston",
                name:         "KSM26RS8L/8MEI",
                price:        60.05,
                typ:          MemoryType::DDR4_2667,
                size:         8 * 1024 * 1024 * 1024,
            },
            Memory {
                manufacturer: "Supermicro",
                name:         "MEM-DR416L-CV02-ER26",
                price:        90.50,
                typ:          MemoryType::DDR4_2667,
                size:         16 * 1024 * 1024 * 1024,
            },
            Memory {
                manufacturer: "Supermicro",
                name:         "MEM-DR432L-CL01-ER29",
                price:        192.00,
                typ:          MemoryType::DDR4_2933,
                size:         32 * 1024 * 1024 * 1024,
            },
        ];

        let processors = [
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-3275M Processor",
                price: 7453.00,
                clock_rate: 2.50,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 28,
                threads: 56,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA3647,
                scalability: 1,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-3275 Processor",
                price: 4449.00,
                clock_rate: 2.50,
                turbo_rate: None,
                avx512_rate: Some(1.6),
                avx512_turbo_rate: Some(2.2),
                cores: 28,
                threads: 56,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA3647,
                scalability: 1,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-3265M Processor",
                price: 6353.00,
                clock_rate: 2.70,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 24,
                threads: 48,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA3647,
                scalability: 1,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-3265 Processor",
                price: 3349.00,
                clock_rate: 2.70,
                turbo_rate: None,
                avx512_rate: Some(1.8),
                avx512_turbo_rate: Some(2.4),
                cores: 24,
                threads: 48,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA3647,
                scalability: 1,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-3245M Processor",
                price: 5002.00,
                clock_rate: 3.20,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 16,
                threads: 32,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA3647,
                scalability: 1,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-3245 Processor",
                price: 1999.00,
                clock_rate: 3.20,
                turbo_rate: None,
                avx512_rate: Some(2.3),
                avx512_turbo_rate: Some(2.8),
                cores: 16,
                threads: 32,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA3647,
                scalability: 1,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-3235 Processor",
                price: 1398.00,
                clock_rate: 3.30,
                turbo_rate: None,
                avx512_rate: Some(2.5),
                avx512_turbo_rate: Some(3.0),
                cores: 12,
                threads: 24,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA3647,
                scalability: 1,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-3225 Processor",
                price: 1199.00,
                clock_rate: 3.70,
                turbo_rate: None,
                avx512_rate: Some(2.8),
                avx512_turbo_rate: Some(3.5),
                cores: 8,
                threads: 16,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA3647,
                scalability: 1,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-3223 Processor",
                price: 749.00,
                clock_rate: 3.50,
                turbo_rate: None,
                avx512_rate: Some(2.5),
                avx512_turbo_rate: Some(3.0),
                cores: 8,
                threads: 16,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA3647,
                scalability: 1,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-3175X Processor",
                price: 2999.00,
                clock_rate: 3.10,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 28,
                threads: 56,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA3647,
                scalability: 1,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-2295 Processor",
                price: 1333.00,
                clock_rate: 3.00,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 18,
                threads: 36,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA2066,
                scalability: 1,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 4,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-2275 Processor",
                price: 1112.00,
                clock_rate: 3.30,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 14,
                threads: 28,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA2066,
                scalability: 1,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 4,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-2265 Processor",
                price: 944.00,
                clock_rate: 3.50,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 12,
                threads: 24,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA2066,
                scalability: 1,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 4,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-2255 Processor",
                price: 778.00,
                clock_rate: 3.70,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 10,
                threads: 20,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA2066,
                scalability: 1,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 4,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-2245 Processor",
                price: 667.00,
                clock_rate: 3.90,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 8,
                threads: 16,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA2066,
                scalability: 1,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 4,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-2235 Processor",
                price: 555.00,
                clock_rate: 3.80,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 6,
                threads: 12,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA2066,
                scalability: 1,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 4,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-2225 Processor",
                price: 444.00,
                clock_rate: 4.10,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 4,
                threads: 8,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA2066,
                scalability: 1,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 4,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-2223 Processor",
                price: 294.00,
                clock_rate: 3.60,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 4,
                threads: 8,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA2066,
                scalability: 1,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 4,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-2195 Processor",
                price: 2553.00,
                clock_rate: 2.30,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 18,
                threads: 36,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA2066,
                scalability: 1,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 4,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-2175 Processor",
                price: 1947.00,
                clock_rate: 2.50,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 14,
                threads: 28,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA2066,
                scalability: 1,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 4,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-2155 Processor",
                price: 1440.00,
                clock_rate: 3.30,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 10,
                threads: 20,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA2066,
                scalability: 1,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 4,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-2145 Processor",
                price: 1113.00,
                clock_rate: 3.70,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 8,
                threads: 16,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA2066,
                scalability: 1,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 4,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-2135 Processor",
                price: 835.00,
                clock_rate: 3.70,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 6,
                threads: 12,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA2066,
                scalability: 1,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 4,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-2133 Processor",
                price: 617.00,
                clock_rate: 3.60,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 6,
                threads: 12,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA2066,
                scalability: 1,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 4,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-2125 Processor",
                price: 444.00,
                clock_rate: 4.00,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 4,
                threads: 8,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA2066,
                scalability: 1,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 4,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® W-2123 Processor",
                price: 294.00,
                clock_rate: 3.60,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 4,
                threads: 8,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonW_FCLGA2066,
                scalability: 1,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 4,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Platinum 8280L Processor",
                price: 13012.00,
                clock_rate: 2.70,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 28,
                threads: 56,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 8,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Platinum 8280 Processor",
                price: 10009.00,
                clock_rate: 2.70,
                turbo_rate: None,
                avx512_rate: Some(1.8),
                avx512_turbo_rate: Some(2.4),
                cores: 28,
                threads: 56,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 8,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Platinum 8276L Processor",
                price: 11722.00,
                clock_rate: 2.20,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 28,
                threads: 56,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 8,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Platinum 8276 Processor",
                price: 8719.00,
                clock_rate: 2.20,
                turbo_rate: None,
                avx512_rate: Some(1.3),
                avx512_turbo_rate: Some(2.1),
                cores: 28,
                threads: 56,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 8,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Platinum 8270 Processor",
                price: 7405.00,
                clock_rate: 2.70,
                turbo_rate: None,
                avx512_rate: Some(1.8),
                avx512_turbo_rate: Some(2.4),
                cores: 26,
                threads: 52,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 8,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Platinum 8268 Processor",
                price: 6302.00,
                clock_rate: 2.90,
                turbo_rate: None,
                avx512_rate: Some(1.9),
                avx512_turbo_rate: Some(2.6),
                cores: 24,
                threads: 48,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 8,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Platinum 8260Y Processor",
                price: 5320.00,
                clock_rate: 2.40,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 24,
                threads: 48,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 8,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Platinum 8260L Processor",
                price: 7705.00,
                clock_rate: 2.40,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 24,
                threads: 48,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 8,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Platinum 8260 Processor",
                price: 4702.00,
                clock_rate: 2.40,
                turbo_rate: None,
                avx512_rate: Some(1.5),
                avx512_turbo_rate: Some(2.3),
                cores: 24,
                threads: 48,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 8,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Platinum 8256 Processor",
                price: 7007.00,
                clock_rate: 3.80,
                turbo_rate: None,
                avx512_rate: Some(2.7),
                avx512_turbo_rate: Some(3.5),
                cores: 4,
                threads: 8,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 8,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Platinum 8253 Processor",
                price: 3115.00,
                clock_rate: 2.20,
                turbo_rate: None,
                avx512_rate: Some(1.2),
                avx512_turbo_rate: Some(1.6),
                cores: 16,
                threads: 32,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 8,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6262V Processor",
                price: 2900.00,
                clock_rate: 1.90,
                turbo_rate: None,
                avx512_rate: Some(1.1),
                avx512_turbo_rate: Some(1.9),
                cores: 24,
                threads: 48,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2400,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6258R Processor",
                price: 3950.00,
                clock_rate: 2.70,
                turbo_rate: None,
                avx512_rate: Some(1.8),
                avx512_turbo_rate: Some(2.5),
                cores: 28,
                threads: 56,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6256 Processor",
                price: 3900.00,
                clock_rate: 3.60,
                turbo_rate: None,
                avx512_rate: Some(2.7),
                avx512_turbo_rate: Some(3.3),
                cores: 12,
                threads: 24,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6254 Processor",
                price: 3803.00,
                clock_rate: 3.10,
                turbo_rate: None,
                avx512_rate: Some(2.2),
                avx512_turbo_rate: Some(2.9),
                cores: 18,
                threads: 36,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6252N Processor",
                price: 1788.00,
                clock_rate: 2.30,
                turbo_rate: None,
                avx512_rate: Some(1.4),
                avx512_turbo_rate: Some(2.3),
                cores: 24,
                threads: 48,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6252 Processor",
                price: 3655.00,
                clock_rate: 2.10,
                turbo_rate: None,
                avx512_rate: Some(1.3),
                avx512_turbo_rate: Some(2.0),
                cores: 24,
                threads: 48,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6250L Processor",
                price: 6404.00,
                clock_rate: 3.90,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 8,
                threads: 16,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6250 Processor",
                price: 3400.00,
                clock_rate: 3.90,
                turbo_rate: None,
                avx512_rate: Some(3.1),
                avx512_turbo_rate: Some(3.8),
                cores: 8,
                threads: 16,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6248R Processor",
                price: 2700.00,
                clock_rate: 3.00,
                turbo_rate: None,
                avx512_rate: Some(2.0),
                avx512_turbo_rate: Some(2.6),
                cores: 24,
                threads: 48,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6248 Processor",
                price: 3072.00,
                clock_rate: 2.50,
                turbo_rate: None,
                avx512_rate: Some(1.6),
                avx512_turbo_rate: Some(2.5),
                cores: 20,
                threads: 40,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6246R Processor",
                price: 3286.00,
                clock_rate: 3.40,
                turbo_rate: None,
                avx512_rate: Some(2.5),
                avx512_turbo_rate: Some(3.1),
                cores: 16,
                threads: 32,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6246 Processor",
                price: 3286.00,
                clock_rate: 3.30,
                turbo_rate: None,
                avx512_rate: Some(2.4),
                avx512_turbo_rate: Some(3.4),
                cores: 12,
                threads: 24,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6244 Processor",
                price: 2925.00,
                clock_rate: 3.60,
                turbo_rate: None,
                avx512_rate: Some(2.6),
                avx512_turbo_rate: Some(3.5),
                cores: 8,
                threads: 16,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6242R Processor",
                price: 2529.00,
                clock_rate: 3.10,
                turbo_rate: None,
                avx512_rate: Some(2.2),
                avx512_turbo_rate: Some(2.9),
                cores: 20,
                threads: 40,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6242 Processor",
                price: 2529.00,
                clock_rate: 2.80,
                turbo_rate: None,
                avx512_rate: Some(1.9),
                avx512_turbo_rate: Some(2.5),
                cores: 16,
                threads: 32,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6240Y Processor",
                price: 2726.00,
                clock_rate: 2.60,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 18,
                threads: 36,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6240R Processor",
                price: 2200.00,
                clock_rate: 2.40,
                turbo_rate: None,
                avx512_rate: Some(1.5),
                avx512_turbo_rate: Some(2.5),
                cores: 24,
                threads: 48,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6240L Processor",
                price: 5448.00,
                clock_rate: 2.60,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 18,
                threads: 36,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6240 Processor",
                price: 2445.00,
                clock_rate: 2.60,
                turbo_rate: None,
                avx512_rate: Some(1.6),
                avx512_turbo_rate: Some(2.5),
                cores: 18,
                threads: 36,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6238T Processor",
                price: 2742.00,
                clock_rate: 1.90,
                turbo_rate: None,
                avx512_rate: Some(1.1),
                avx512_turbo_rate: Some(1.8),
                cores: 22,
                threads: 44,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6238R Processor",
                price: 2612.00,
                clock_rate: 2.20,
                turbo_rate: None,
                avx512_rate: Some(1.3),
                avx512_turbo_rate: Some(2.1),
                cores: 28,
                threads: 56,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6238L Processor",
                price: 5615.00,
                clock_rate: 2.10,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 22,
                threads: 44,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6238 Processor",
                price: 2612.00,
                clock_rate: 2.10,
                turbo_rate: None,
                avx512_rate: Some(1.3),
                avx512_turbo_rate: Some(2.1),
                cores: 22,
                threads: 44,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6234 Processor",
                price: 2214.00,
                clock_rate: 3.30,
                turbo_rate: None,
                avx512_rate: Some(2.3),
                avx512_turbo_rate: Some(3.1),
                cores: 8,
                threads: 16,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6230T Processor",
                price: 1988.00,
                clock_rate: 2.10,
                turbo_rate: None,
                avx512_rate: Some(1.1),
                avx512_turbo_rate: Some(2.0),
                cores: 20,
                threads: 40,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6230N Processor",
                price: 1452.00,
                clock_rate: 2.30,
                turbo_rate: None,
                avx512_rate: Some(1.2),
                avx512_turbo_rate: Some(2.2),
                cores: 20,
                threads: 40,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6230R Processor",
                price: 1894.00,
                clock_rate: 2.10,
                turbo_rate: None,
                avx512_rate: Some(1.3),
                avx512_turbo_rate: Some(2.3),
                cores: 26,
                threads: 52,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6230 Processor",
                price: 1894.00,
                clock_rate: 2.10,
                turbo_rate: None,
                avx512_rate: Some(1.1),
                avx512_turbo_rate: Some(2.0),
                cores: 20,
                threads: 40,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6226R Processor",
                price: 1300.00,
                clock_rate: 2.90,
                turbo_rate: None,
                avx512_rate: Some(1.9),
                avx512_turbo_rate: Some(2.5),
                cores: 16,
                threads: 32,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6226 Processor",
                price: 1776.00,
                clock_rate: 2.70,
                turbo_rate: None,
                avx512_rate: Some(1.9),
                avx512_turbo_rate: Some(2.6),
                cores: 12,
                threads: 24,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6222V Processor",
                price: 1600.00,
                clock_rate: 1.80,
                turbo_rate: None,
                avx512_rate: Some(1.1),
                avx512_turbo_rate: Some(1.8),
                cores: 20,
                threads: 40,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2400,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 6208U Processor",
                price: 989.00,
                clock_rate: 2.90,
                turbo_rate: None,
                avx512_rate: Some(1.9),
                avx512_turbo_rate: Some(2.5),
                cores: 16,
                threads: 32,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 1,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 5222 Processor",
                price: 1221.00,
                clock_rate: 3.80,
                turbo_rate: None,
                avx512_rate: Some(2.7),
                avx512_turbo_rate: Some(3.5),
                cores: 4,
                threads: 8,
                avx512_fma_units: Some(2),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2933,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 5220T Processor",
                price: 1727.00,
                clock_rate: 1.90,
                turbo_rate: None,
                avx512_rate: Some(1.1),
                avx512_turbo_rate: Some(2.1),
                cores: 18,
                threads: 36,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 5220S Processor",
                price: 2000.00,
                clock_rate: 2.70,
                turbo_rate: None,
                avx512_rate: Some(1.4),
                avx512_turbo_rate: Some(2.1),
                cores: 18,
                threads: 36,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 5220R Processor",
                price: 1555.00,
                clock_rate: 2.20,
                turbo_rate: None,
                avx512_rate: Some(1.4),
                avx512_turbo_rate: Some(2.4),
                cores: 24,
                threads: 48,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 5220 Processor",
                price: 1555.00,
                clock_rate: 2.20,
                turbo_rate: None,
                avx512_rate: Some(1.4),
                avx512_turbo_rate: Some(2.1),
                cores: 18,
                threads: 36,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 5218T Processor",
                price: 1349.00,
                clock_rate: 2.10,
                turbo_rate: None,
                avx512_rate: Some(1.3),
                avx512_turbo_rate: Some(2.0),
                cores: 16,
                threads: 32,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 5218R Processor",
                price: 1273.00,
                clock_rate: 2.10,
                turbo_rate: None,
                avx512_rate: Some(1.1),
                avx512_turbo_rate: Some(2.3),
                cores: 20,
                threads: 40,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 5218N Processor",
                price: 1218.00,
                clock_rate: 2.30,
                turbo_rate: None,
                avx512_rate: Some(1.2),
                avx512_turbo_rate: Some(2.5),
                cores: 16,
                threads: 32,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 5218B Processor",
                price: 1273.00,
                clock_rate: 2.30,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 16,
                threads: 32,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 5218 Processor",
                price: 1273.00,
                clock_rate: 2.30,
                turbo_rate: None,
                avx512_rate: Some(1.5),
                avx512_turbo_rate: Some(2.1),
                cores: 16,
                threads: 32,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 5217 Processor",
                price: 1522.00,
                clock_rate: 3.00,
                turbo_rate: None,
                avx512_rate: Some(2.0),
                avx512_turbo_rate: Some(2.4),
                cores: 8,
                threads: 16,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 5215L Processor",
                price: 4224.00,
                clock_rate: 2.50,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 10,
                threads: 20,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Gold 5215 Processor",
                price: 1221.00,
                clock_rate: 2.50,
                turbo_rate: None,
                avx512_rate: Some(1.4),
                avx512_turbo_rate: Some(1.8),
                cores: 10,
                threads: 20,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 4,
                mem_support: MemoryType::DDR4_2667,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Silver 4216 Processor",
                price: 900.00,
                clock_rate: 2.10,
                turbo_rate: None,
                avx512_rate: Some(1.1),
                avx512_turbo_rate: Some(1.6),
                cores: 16,
                threads: 32,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2400,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Silver 4215R Processor",
                price: 794.00,
                clock_rate: 3.20,
                turbo_rate: None,
                avx512_rate: Some(1.5),
                avx512_turbo_rate: Some(2.0),
                cores: 8,
                threads: 16,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2400,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Silver 4215 Processor",
                price: 562.00,
                clock_rate: 2.50,
                turbo_rate: None,
                avx512_rate: Some(1.5),
                avx512_turbo_rate: Some(2.0),
                cores: 8,
                threads: 16,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2400,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Silver 4214Y Processor",
                price: 768.00,
                clock_rate: 2.20,
                turbo_rate: None,
                avx512_rate: None,
                avx512_turbo_rate: None,
                cores: 12,
                threads: 24,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2400,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Silver 4214R Processor",
                price: 694.00,
                clock_rate: 2.40,
                turbo_rate: None,
                avx512_rate: Some(1.6),
                avx512_turbo_rate: Some(1.9),
                cores: 12,
                threads: 24,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2400,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Silver 4214 Processor",
                price: 694.00,
                clock_rate: 2.20,
                turbo_rate: None,
                avx512_rate: Some(1.3),
                avx512_turbo_rate: Some(1.6),
                cores: 12,
                threads: 24,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2400,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Silver 4210T Processor",
                price: 555.00,
                clock_rate: 2.30,
                turbo_rate: None,
                avx512_rate: Some(1.2),
                avx512_turbo_rate: Some(2.2),
                cores: 10,
                threads: 20,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2400,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Silver 4210R Processor",
                price: 501.00,
                clock_rate: 2.40,
                turbo_rate: None,
                avx512_rate: Some(1.4),
                avx512_turbo_rate: Some(1.7),
                cores: 10,
                threads: 20,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2400,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Silver 4210 Processor",
                price: 501.00,
                clock_rate: 2.20,
                turbo_rate: None,
                avx512_rate: Some(1.2),
                avx512_turbo_rate: Some(1.5),
                cores: 10,
                threads: 20,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2400,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Silver 4209T Processor",
                price: 501.00,
                clock_rate: 2.20,
                turbo_rate: None,
                avx512_rate: Some(1.2),
                avx512_turbo_rate: Some(1.5),
                cores: 8,
                threads: 16,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2400,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Silver 4208 Processor",
                price: 417.00,
                clock_rate: 2.10,
                turbo_rate: None,
                avx512_rate: Some(1.1),
                avx512_turbo_rate: Some(1.4),
                cores: 8,
                threads: 16,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2400,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Bronze 3206R Processor",
                price: 306.00,
                clock_rate: 1.90,
                turbo_rate: None,
                avx512_rate: Some(1.5),
                avx512_turbo_rate: Some(1.5),
                cores: 8,
                threads: 8,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2133,
                mem_channels: 6,
            },
            Processor {
                manufacturer: "Intel",
                name: "Intel® Xeon® Bronze 3204 Processor",
                price: 213.00,
                clock_rate: 1.90,
                turbo_rate: None,
                avx512_rate: Some(1.0),
                avx512_turbo_rate: Some(1.0),
                cores: 6,
                threads: 6,
                avx512_fma_units: Some(1),
                typ: ProcessorType::XeonScalableV2_FCLGA3647,
                scalability: 2,
                mem_support: MemoryType::DDR4_2133,
                mem_channels: 6,
            },
        ];

        Database {
            systems:      systems[..].into(),
            blades:       blades[..].into(),
            motherboards: motherboards[..].into(),
            memory:       memory[..].into(),
            processors:   processors[..].into(),
        }
    }

    /// Create a random system
    pub fn random_system(&self) -> Option<System> {
        // Pick a random system
        let mut system = self.systems[
            random::<usize>() % self.systems.len()].clone();

        // Make sure that this system isn't pre-defined with a set blade
        // configuration.
        if system.blades.len() == 0 {
            // Pick a random amount of compatible blades for this system
            let mut num_blades = random::<u8>() % system.num_blades + 1;

            let mut visited_blades = BTreeSet::new();
            while num_blades > 0 {
                // Could not find a compatiable blade
                if system.blades.len() == 0 &&
                        visited_blades.len() == self.blades.len() {
                    return None;
                }

                // Randomly pick a blade for this system
                let sel = random::<usize>() % self.blades.len();
                let blade = &self.blades[sel];
                visited_blades.insert(sel);

                // If this blade is not compatible, go to the next blade
                if blade.blade_type != system.blade_type {
                    continue;
                }

                // Add the blade to the system
                system.blades.push(blade.clone());
                num_blades -= 1;
            }
        }

        for blade in system.blades.iter_mut() {
            // Skip pre-configured motherboards
            if blade.motherboard.is_some() { continue; }

            let mut visited = BTreeSet::new();
            loop {
                // Check if we ran out of options
                if visited.len() == self.motherboards.len() {
                    return None;
                }

                // Pick a random motherboard
                let sel = random::<usize>() % self.motherboards.len();
                let motherboard = &self.motherboards[sel];
                visited.insert(sel);

                // If it's compatible, it's the one we use!
                if blade.mb_form_factor.contains(&motherboard.form_factor) {
                    blade.motherboard = Some(motherboard.clone());
                    break;
                }
            }
        }

        for blade in system.blades.iter_mut() {
            // Get access to the motherboard
            let motherboard = blade.motherboard.as_mut().unwrap();

            // Pick a processor
            let mut visited = BTreeSet::new();
            let proc = loop {
                // Check if we ran out of options
                if visited.len() == self.processors.len() {
                    return None;
                }

                // Pick a random processor
                let sel = random::<usize>() % self.processors.len();
                let processor = &self.processors[sel];
                visited.insert(sel);

                // If it's compatible, it's the one we use!
                if motherboard.proc_support == processor.typ {
                    break processor;
                }
            };

            let max_scale =
                std::cmp::min(motherboard.scalability, proc.scalability);
            let num_procs = random::<u8>() % max_scale + 1;
            (0..num_procs).for_each(|_| {
                motherboard.processors.push(proc.clone())
            });
        }
        
        for blade in system.blades.iter_mut() {
            // Get access to the motherboard
            let motherboard = blade.motherboard.as_mut().unwrap();

            // Get access to a single processor
            let proc = &motherboard.processors[0];
            
            // Pick memory
            let mut visited = BTreeSet::new();
            let mem = loop {
                // Check if we ran out of options
                if visited.len() == self.memory.len() {
                    return None;
                }

                // Pick a random stick of RAM
                let sel = random::<usize>() % self.memory.len();
                let mem = &self.memory[sel];
                visited.insert(sel);

                // If it's compatible, it's the one we use!
                if mem.typ.class() == proc.mem_support.class() {
                    break mem;
                }
            };

            // Compute DIMMs per CPU
            let dimms_per_cpu =
                motherboard.memory_sockets / motherboard.scalability;

            // Compute max DIMMs per CPU based on channels on the CPU
            let max_dimms = std::cmp::min(proc.mem_channels, dimms_per_cpu);

            // Pick a random number of DIMMs
            let num_dimms = random::<u8>() % max_dimms + 1;

            // For each populated socket, add this many DIMMs
            for _ in 0..motherboard.processors.len() {
                (0..num_dimms).for_each(|_| {
                    motherboard.memory.push(mem.clone());
                });
            }
        }

        // Make all blades identical
        let template = system.blades[0].clone();
        system.blades.iter_mut().for_each(|x| *x = template.clone());

        Some(system)
    }
}

